### ISSUE TITLE
Error when there is no device to add

### ISSUE THREAD

**Issue by lsobota** [lsobota/CentralDevice#15]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/pi/MasterThesis/CentralDevice/central_device.py", line 118, in run
    self.handle_BLEResponse(order)
  File "/home/pi/MasterThesis/CentralDevice/central_device.py", line 101, in handle_BLEResponse
    device['id'] = len(self.devices)
TypeError: 'NoneType' object does not support item assignment

**Comment by lsobota** [comment]
Solved.
