### ISSUE TITLE
Debug connect is not working properly

### ISSUE THREAD

**Issue by lsobota** [lsobota/CentralDevice#25]
Somehow incorrect ID handling is wrong (or maybe just 0-value is correct?). Needs investigation.

Welcome to interactive driver mode
Supported command: scan, filter, connect, disconnect, disconnect_all, read, read_all, write, devlist, exit
action >> scan 1
BLEDelegate Found new device
BLEDelegate Address: b8:bb:af:e4:b1:c8 || Type: public || Rssi: -76
BLEDelegate Found new device
BLEDelegate Address: 68:27:37:ab:fe:35 || Type: public || Rssi: -90
BLEDelegate Found new device
BLEDelegate Address: e7:1f:32:a6:ef:f3 || Type: random || Rssi: -40
BLEDriver Scan stopped
action >> connect 2
Traceback (most recent call last):
  File "ble_driver.py", line 283, in <module>
    driver.debug_run()
  File "ble_driver.py", line 270, in debug_run
    self._execute(action, args)
  File "ble_driver.py", line 140, in _execute
    foo(*args)
  File "ble_driver.py", line 167, in connect
    device = self.driver.devices[arg]
TypeError: 'dict_values' object does not support indexing

-------------------------------------------------------------------------

Welcome to interactive driver mode
Supported command: scan, filter, connect, disconnect, disconnect_all, read, read_all, write, devlist, exit
action >> scan
BLEDelegate Found new device
BLEDelegate Address: 68:27:37:ab:fe:35 || Type: public || Rssi: -92
BLEDelegate Found new device
BLEDelegate Address: b8:bb:af:e4:b1:c8 || Type: public || Rssi: -88
BLEDelegate Found new device
BLEDelegate Address: e7:1f:32:a6:ef:f3 || Type: random || Rssi: -41
f       BLEDriver Scan stopped
action >> filter
BLEDriver Device: b8:bb:af:e4:b1:c8
BLEDriver     Rejected
BLEDriver Device: e7:1f:32:a6:ef:f3
BLEDriver     Compatible!
BLEDriver Device: 68:27:37:ab:fe:35
BLEDriver     Rejected
action >> connect 0
BLEDriver Connected to device: e7:1f:32:a6:ef:f3

**Comment by lsobota** [comment]
Needs to be confirmed due to BLE rework. Close for now.
